In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2020-financial-year-provisional/Download-data/annual-enterprise-survey-2020-financial-year-provisional-csv.csv")

In [3]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"733,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"660,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,872",ANZSIC06 divisions A-S (excluding classes K633...

In [19]:
df['Industry_aggregation_NZSIOC']

0        Level 1
1        Level 1
2        Level 1
3        Level 1
4        Level 1
          ...
37075    Level 3
37076    Level 3
37077    Level 3
37078    Level 3
37079    Level 3
Name: Industry_aggregation_NZSIOC, Length: 37080, dtype: object

In [22]:
df.sort_values('Industry_code_NZSIOC', ascending = False).head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
9240,2019,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H08,Total expenditure,Financial performance,"42,859","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4616,2020,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H23,Surplus before income tax,Financial performance,"2,685","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4615,2020,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H22,Closing stocks,Financial performance,"5,831","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4614,2020,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H21,Opening stocks,Financial performance,"4,981","ANZSIC06 groups C111, C112, C113, C114, C115, ..."